name: buildtrackr
description: "Track Construction Site."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  path_provider: ^2.0.11
  devicelocale: ^0.5.2
  intl: ^0.17.0
  firebase_auth: ^4.7.0
  firebase_database: ^10.2.4
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  firebase_app_check: ^0.1.5+2
  url_launcher: ^6.1.6
  decorated_icon: ^1.2.1
  flutter_svprogresshud: ^1.0.0
  vibration: ^1.7.4-nullsafety.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  provider: ^6.0.3
  photo_view: ^0.14.0
  flutter_native_splash: ^2.2.17
  connectivity_plus: ^2.3.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/graphics/
    - assets/flags/
    - assets/raw/

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
          style: normal

    - family: GilroyHeavy
      fonts:
        - asset: fonts/Gilroy-Heavy.ttf
          style: normal

    - family: Alliance
      fonts:
        - asset: fonts/Alliance.ttf
          weight: 700
    - family: Bourbon
      fonts:
        - asset: fonts/Bourbon.otf
          style: normal
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
          style: normal
    - family: Yantramanav Thin
      fonts:
        - asset: fonts/Yantramanav-Thin.ttf
          style: normal
    - family: RobotoSlab-Thin
      fonts:
        - asset: fonts/RobotoSlab-Thin.ttf
          style: normal